spring.application.name=MyMemory

spring.datasource.url=jdbc:postgresql://ep-calm-dream-a1wprshl-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_DsbfZwMeg5a4

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
