spring.application.name=MyMemory
spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=postgres
spring.datasource.password=25642564
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true