spring.application.name=MyMemory

spring.datasource.url=jdbc:postgresql://ep-gentle-lab-a1c0328g-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ogYZ6vhtP2wI

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
